name: dart_vlc
description: Flutter media playback, broadcast, recording & chromecast library. Based on libvlc.
version: 0.3.0+1
homepage: https://github.com/alexmercerind/dart_vlc
repository: https://github.com/alexmercerind/dart_vlc
documentation: https://github.com/alexmercerind/dart_vlc/blob/master/README.md

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
 # dart_vlc_ffi: ^0.1.8
  path: ^1.8.2
  path_provider: ^2.0.11
  audio_video_progress_bar: ^0.10.0
  flutter_native_view: ^0.0.2
  window_manager: ^0.2.6
  dart_vlc_ffi:
    path: ./ffi

flutter:
  # No platform channel implementation after migration to FFI.
  plugin:
    platforms:
      windows:
        pluginClass: DartVlcPlugin
      linux:
        pluginClass: DartVlcPlugin
